### PR TITLE
Add vec definition instead of relying on StaticArrays

### LINKED ISSUE #100: `vec(::SLVector)` fails with StaticArrays 1.2 (but succeeds with StaticArrays <1.2)
```julia
julia> using LabelledArrays

julia> ABC = @SLVector (:a,:b,:c)
SLArray{Tuple{3}, (:a, :b, :c), N, L, Syms} where {N, L, Syms}

julia> A = ABC(1,2,3)
3-element SLArray{Tuple{3}, Int64, 1, 3, (:a, :b, :c)} with indices SOneTo(3):
 :a => 1
 :b => 2
 :c => 3

julia> A === vec(A)
true

(staticarrays) pkg> st StaticArrays LabelledArrays
      Status `~/Documents/progwork/julia/env/staticarrays/Project.toml`
  [2ee39098] LabelledArrays v1.6.2
  [90137ffa] StaticArrays v1.1.3
```
```julia
julia> using LabelledArrays

julia> ABC = @SLVector (:a,:b,:c)
SLArray{Tuple{3}, (:a, :b, :c), N, L, Syms} where {N, L, Syms}

julia> A = ABC(1,2,3)
3-element SLArray{Tuple{3}, Int64, 1, 3, (:a, :b, :c)} with indices SOneTo(3):
 :a => 1
 :b => 2
 :c => 3

julia> vec(A)
ERROR: ArgumentError: invalid index: nothing of type Nothing
Stacktrace:
  [1] to_index(i::Nothing)
    @ Base ./indices.jl:300
  [2] to_index(A::SVector{3, Int64}, i::Nothing)
    @ Base ./indices.jl:277
  [3] to_indices
    @ ./indices.jl:333 [inlined]
  [4] to_indices
    @ ./indices.jl:325 [inlined]
  [5] view
    @ ./subarray.jl:176 [inlined]
  [6] maybeview
    @ ./views.jl:133 [inlined]
  [7] macro expansion
    @ ~/.julia/packages/LabelledArrays/2gcYl/src/LabelledArrays.jl:15 [inlined]
  [8] __getindex
    @ ~/.julia/packages/LabelledArrays/2gcYl/src/LabelledArrays.jl:9 [inlined]
  [9] getindex
    @ ~/.julia/packages/LabelledArrays/2gcYl/src/slarray.jl:91 [inlined]
 [10] getproperty
    @ ~/.julia/packages/LabelledArrays/2gcYl/src/slarray.jl:86 [inlined]
 [11] SizedArray
    @ ~/.julia/packages/StaticArrays/AHT47/src/convert.jl:6 [inlined]
 [12] __reshape
    @ ~/.julia/packages/StaticArrays/AHT47/src/abstractarray.jl:193 [inlined]
 [13] reshape
    @ ~/.julia/packages/StaticArrays/AHT47/src/abstractarray.jl:187 [inlined]
 [14] vec(a::SLArray{Tuple{3}, Int64, 1, 3, (:a, :b, :c)})
    @ StaticArrays ~/.julia/packages/StaticArrays/AHT47/src/abstractarray.jl:204
 [15] top-level scope
    @ REPL[4]:1

(staticarrays) pkg> st StaticArrays LabelledArrays
      Status `~/Documents/progwork/julia/env/staticarrays/Project.toml`
  [2ee39098] LabelledArrays v1.6.2
  [90137ffa] StaticArrays v1.2.7
```

### PR DESCRIPTION
**Pull request by chriselrod**
fixes #100
Maybe it'd be better to spend the time to figure out what went wrong in StaticArrays, but I find it tends to take several weeks to get anything merged into StaticArrays, and defining a one liner is easy.

### CODE REVIEW

**Comment by mateuszbaran** [comment]
I'd suggest defining `reshape` instead: `@inline reshape(a::SLArray, s::Size) = similar_type(a, s)(Tuple(a))`. StaticArrays no longer makes a copy by default when reshaping.

**Comment by chriselrod** [comment]
Thanks, I saw your comment: https://github.com/JuliaArrays/StaticArrays.jl/commit/1c72f5c26fd3bcc4006b38a3c583b43e65756418#commitcomment-54021728
and made the suggested change.

**Comment by chriselrod** [comment]
I applied the change to the mutable `LArray`s as well, as I figured not being able to mutate the parent array is less likely to be breaking at the moment than losing labels is.

**Comment by andreasnoack** [comment]
I'm wondering if this would just work without adding special methods here if https://github.com/JuliaArrays/StaticArrays.jl/issues/943 was fixed

**Comment by chriselrod** [comment]
Does our code rely on having the labels? I know DiffEq moved broadly towards favoring integer indexing.

**Comment by mateuszbaran** [comment]
> I applied the change to the mutable `LArray`s as well, as I figured not being able to mutate the parent array is less likely to be breaking at the moment than losing labels is.

`LArray` isn't a `StaticArray`, are you sure it's correct?

> I'm wondering if this would just work without adding special methods here if [JuliaArrays/StaticArrays.jl#943](https://github.com/JuliaArrays/StaticArrays.jl/issues/943) was fixed

I think fixing that would just make reshaping of `SLArray` return an `SizedArray` instead of throwing an error.

**Comment by chriselrod** [comment]
> `LArray` isn't a `StaticArray`, are you sure it's correct?

Ha, I didn't actually try it. Yes, that method is probably never called.

> I think fixing that would just make reshaping of SLArray return a SizedArray instead of throwing an error.

I don't know offhand, so I'd have to test if code is relying on the labels.
Although it would probably be preferable to keep the labels in general.

**Comment by ChrisRackauckas** [comment]
>Does our code rely on having the labels? I know DiffEq moved broadly towards favoring integer indexing.

It does, in the broadcast of the `@model` macro and then in the named indexing of the simobs return. I think it would be best to fix that and remove LabelledArrays, but it's a bit hard and the names are just easy.

**Pull request merged**
